---
title: "ProjectDDP"
author: "arnela82"
date: "8/2/2020"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introducing

This is the project for Developing Data Product course.As part of this, I have created a shiny app and deployed it on the shiny server. The link is https://arnela.shinyapps.io/Project4/.  The code can be found at 

## Overview

The shiny app shows boxplot and part of regression model for different variables from mtcars dataset.

```{r}
head(mtcars)
```


## UI code

```{r echo=TRUE, warning=FALSE, message=FALSE, eval=FALSE}
library(shiny)

# Define UI for application that draws a histogram
shinyUI(fluidPage(

    # Application title
    titlePanel("Cars dataset - Miles per Gallon"),

    sidebarLayout(
        sidebarPanel(
            selectInput("variable", "Variable:",
                        c("Cylinders"="cyl",
                          "Transmission"="am",
                          "Gears" = "gear")),
            checkboxInput("outliers", "Show BoxPlot's outliers", FALSE)
        ),

        # Show a plot of the generated distribution
        mainPanel(
            #Text output:
            h3(textOutput("Caption")),
            
            tabsetPanel(type = "tabs",
                        tabPanel("BoxPlot", plotOutput("mpgBoxPlot")),
                        tabPanel("Regression model",
                                 plotOutput("mpgPlot"),
                                 verbatimTextOutput("fit")
                                 )
                        )
        )
    )
))
```

##Server Code

```{r echo=TRUE, warning=FALSE, message=FALSE, eval=FALSE}
library(shiny)
library(datasets)

mpgData<- mtcars
mpgData$am<-factor(mpgData$am, labels = c("Automatic", "Manual"))

shinyServer(function(input, output) {

    formulaText <-reactive({
        paste("mpg ~", input$variable)
    })
    
    formulaTextPoint <- reactive({
        paste("mpg~", "as.integer(", input$variable,")")
    })
    
    fit<- reactive({
        lm(as.formula(formulaTextPoint()),data = mpgData)
    })
    
    output$caption <- renderText({
        formulaText()
    })
    
    output$mpgBoxPlot<-renderPlot ({
        boxplot(as.formula(formulaText()),
                data= mpgData,
                outline = input$outliers)
        })
    
    output$fit <- renderPrint({
        summary(fit())
    })
    
    output$mpgplot <- renderPlot({
       with(mpgData, {
           plot(as.formula(formulaTextPoint()))
           abline(fit(), col=2)
       })
         })
    })
        
```

